[package]
name = "rusty-shooter"
version = "0.1.0"
authors = ["Dmitry <d1maxa@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rg3d = { path = "../rg3d" }
glutin = "0.21.0"