[package]
name = "rusty-shooter"
version = "0.1.0"
authors = ["Dmitry <d1maxa@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = false

[dependencies]
rg3d-core = { path = "../rg3d-core" }
rg3d-sound = { path = "../rg3d-sound" }
rg3d = { path = "../rg3d" }
rand = "0.7.0"
glutin = "0.21.0"