[package]
name = "rusty-shooter"
version = "0.1.3"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"

[profile.release]
lto = false

[dependencies]
rg3d-core = { path = "../rg3d-core" }
rg3d-sound = { path = "../rg3d-sound" }
rg3d-physics = { path = "../rg3d-physics" }
rg3d = { path = "../rg3d" }
rand = "0.7.0"